name: vt_simple_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_riverpod:
  freezed_annotation:
  gap:
  go_router:
  http:
  dio:
  intl:
  meta:
  simple_logger:
  shared_preferences:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  go_router_builder:
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/lang/
